### PR TITLE
add model to nodeinfo.hardware

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by jplitza** [comment]
I don't like it. I know, the x86 target of Gluon does this, but that doesn't mean we have to, too.

A CPU is not a model and doesn't tell you much about the capabilities and performance of a device without other values like memory or bandwidth. Also, in statistics, this will only cause fragmentation, because nearly no two servers will use the exact same CPU.

**Comment by genofire** [comment]
Maybe server are virtualized, on this way the have the same CPU 😂 
Could we have a other indicator for hardware model in the server or just a string like `'gateway'` ?

**Comment by genofire** [comment]
Maybe server are virtualized, on this way the have the same CPU 😂 
Could we have a other indicator for hardware model in the server or just a string like `'gateway'` ?

**Comment by jplitza** [comment]
I don't see any advantages in that, sorry.

**Pull request closed without merging**
