### PR TITLE
respondd.py: Fix early interface bind to allow multiple instances

### PR DESCRIPTION
**Pull request by kokel**

### CODE REVIEW

**Comment by jplitza** [comment]
Joining a multicast group on one interface does not automatically bind to that interface. Thus, when using multicast, your patch would direct the request to a random instance if multiple are running, I guess.

Furthermore, if we are using `bind_and_activate=False`, we should also set the `address_family` in the same way we set `allow_reuse_address`.

**Comment by kokel** [comment]
Indeed, first time I tried to run multiple instances of ffnord-alfred-announce I got:

```
Traceback (most recent call last):
  File "respondd.py", line 78, in <module>
    get_handler(args.directory, {'batadv_dev': args.batadv_iface})
  File "/usr/lib/python3.4/socketserver.py", line 430, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/socketserver.py", line 444, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

That's why I assumed the problem was interface bind related.
Nevertheless, my patch is running in our Test-Setup of the ffrgb meshviewer using yanic as a backend.
We serve 2 communities (2 distinct batman-adv meshes) on the same supernodes. 
While using one yanic collector directing requests to a random instance should not be a problem.

**Comment by jplitza** [comment]
With Yanic or actually multicast in general, you will get the right instance. But getting a wrong instance with unicast is a problem, because it will contain useless neighbor info, for example.

**Comment by jplitza** [comment]
Hm, I always had in mind to fix this using `setsockopt(SO_BINDTODEVICE)`, but forgot that the current implementation allows to specify more than one multicast interface, while setsockopt can only bind to one interface. So in order to allow different instances on different interfaces, one would at the same time have to restrict one instance to one interface, or restructure the code to handle multiple sockets at once.

**Pull request closed without merging**
