### PR TITLE
Add respondd capability

### PR DESCRIPTION
**Pull request by jplitza**
Also, in 95e1f57 I added/corrected some values.

### CODE REVIEW

**Comment by jplitza** [comment]
Will anybody at some point review this? Otherwise I'll just merge it.

**Comment by jplitza** [comment]
Okay, I take that as a "no" and merge it myself. We are using the feature for quite some time now, and I haven't heard any complaints.

**Comment by genofire** [comment]
Hello,
I have recognized, the neighbors of the VPN/gateway didn't show up anymore.
At the time I have no much time to debug and could not find another behavior of Alfred.
@ffhb: vpn05 has checkout a version before this merge -> example VPN is maybe vpn02, look at https://ffhb.de/meshviewer/#!v:m;n:2ea097b0c462

Hope it could help

**Comment by jplitza** [comment]
@genofire  I don't see how that could be caused by this PR. Neighbors are not and were never provided by this script collection, but only by batadv-vis. Adding them would be a good point if we want to migrate away from alfred, but I think that they are missing was more likely caused by something else.

**Comment by genofire** [comment]
Would you try on vpn02 and see the wonder? - thx:
```
wget https://raw.githubusercontent.com/ffnord/ffnord-alfred-announce/b31922fd53d2796b69ac4bd260ad837a200d0d5f/nodeinfo.d/network/mesh_interfaces -O /opt/ffhb/alfred-announce/nodeinfo.d/network/mesh_interfaces
```
I do not know, why - have also no idea how batadv-vis work (i just use it till now, sry)

**Comment by jplitza** [comment]
Ah, interesting. The ffmap-backend needs either the old `mesh_interfaces`, or the batman interface needs to be called "bat0" ([source](https://github.com/ffnord/ffmap-backend/blob/master/lib/nodes.py#L10-28)). I'd rather fix that instead. ;-)

**Comment by genofire** [comment]
One question, is this branch still needed?

**Pull request merged**
